# Generated by Django 5.0.1 on 2024-02-05 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_username', models.CharField(max_length=45, unique=True)),
                ('a_name', models.CharField(max_length=45)),
                ('a_access', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_room_number', models.IntegerField()),
                ('o_guest_name', models.CharField(max_length=45)),
                ('o_item_ordered', models.CharField(max_length=45)),
                ('o_quantity', models.IntegerField()),
                ('o_order_date', models.DateTimeField()),
                ('o_status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_username', models.CharField(max_length=45, unique=True)),
                ('u_name', models.CharField(max_length=45)),
                ('u_role', models.CharField(max_length=45)),
                ('u_access', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_room_number', models.IntegerField()),
                ('d_defect_type', models.CharField(max_length=45)),
                ('d_description', models.CharField(blank=True, max_length=245, null=True)),
                ('d_date_reported', models.DateField()),
                ('d_status', models.CharField(max_length=45)),
                ('d_reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deff.user')),
            ],
            options={
                'db_table': 'defects',
            },
        ),
    ]
