# Generated by Django 5.0.1 on 2024-02-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deff', '0002_remove_defect_d_reported_by_remove_user_u_access_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='a_access',
            new_name='u_access',
        ),
        migrations.AlterField(
            model_name='defect',
            name='d_date_reported',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
