# Generated by Django 5.0.1 on 2024-02-09 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deff', '0007_alter_user_id_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='defect',
            name='d_date_reported',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='d_reported_by',
            field=models.ForeignKey(db_column='d_reported_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='deff.user'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='d_status',
            field=models.CharField(choices=[('Прийнято', 'accepted'), ('Виконано', 'completed'), ('В обробці', 'in_progress'), ('Відхилено', 'rejected')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='id_defect',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
